
// vratis mi sve rezervacije
GET http://localhost/bicikle/public/api/rez HTTP/1.1

###
// pretrazi mi rezervacije sa LIKE
GET http://localhost/bicikle/public/api/rez/search/Ra HTTP/1.1
###
//unosi novu rez
POST http://localhost/bicikle/public/api/rez HTTP/1.1
Content-Type: application/json
Accept: application/json

{

"ime":"Ivan",
"prezime":"A",
"datum_preuzimanja":"2023-01-01",
"kontakt":"011123456",
"brDana":"1",
"bicikla_id":"1",
"user_id":"1"

}

###
###
// hocu da promenim rezervaciju sa id-em 1
PUT http://localhost/bicikle/public/api/rez/1
Content-Type: application/json
Accept: application/json

{
"ime":"Marko"
}
###

// hocu da obrisem rezervaciju sa id-em 1
DELETE http://localhost/bicikle/public/api/rez/1

###
// prikazi mi samo rezervaciju sa id-em 1
 GET  http://localhost/bicikle/public/api/rez/1

 ###